// React_JS_crash_course/react-task-tracker/src/components/AddTask.js
import { useState } from 'react'
import { HiOutlineCheckCircle } from "react-icons/hi";


const AddTask = ({ onAdd }) => {
    const [text, setText] = useState('')
    const [day, setDay] = useState('')
    const [reminder, setReminder] = useState(false)

    const onSubmit = (e) => {
        e.preventDefault()

        if (!text) {
            alert('Please add a task')
            return
        }

        onAdd({ text, day, reminder })

        setText('')
        setDay('')
        setReminder(false)
    }

    return (
        <form className="px-4 flex flex-col gap-4" onSubmit={onSubmit}>
            <div className="flex flex-col gap-2">
                <label htmlFor="">Task</label>
                <input type="text" placeholder="Add Task" className="border border-gray-500 px-4 py-2" value={text} onChange={(e) => setText(e.target.value)} />
            </div>
            <div className="flex flex-col gap-2">
                <label htmlFor="">Day</label>
                <input type="text" placeholder="Add Day & Time" className="border border-gray-500 px-4 py-2" value={day} onChange={(e) => setDay(e.target.value)} />
            </div>
            <div className="flex gap-2">
                <label htmlFor="">Set Reminder</label>
                <input type="checkbox" checked={reminder} className="self-start w-6 h-6" value={reminder} onChange={(e) => setReminder(e.currentTarget.checked)} />
            </div>

            <button type="submit" value="Save Task" className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 rounded-md flex justify-center items-center gap-2"><HiOutlineCheckCircle className="w-5 h-5" />Save Task</button>
        </form>
    )
}

export default AddTask

// Vue_JS_crash_course/vue-crash-course/src/components/AddTask.vue
<template>
    <form @submit="onSubmit" action="" class="add-form">
        <div class="form-control">
            <label for="text">Task</label>
            <input v-model="text" type="text" name="text" id="text" placeholder="Add task">
        </div>
        <div class="form-control">
            <label for="day">Day & time</label>
            <input v-model="day" type="text" name="day" id="day" placeholder="Add day & time">
        </div>
        <div class="form-control form-control-check">
            <label for="reminder">Set reminder</label>
            <input v-model="reminder" type="checkbox" name="reminder" id="reminder">
        </div>
        <input type="submit" value="Save task" class="btn btn-block">
    </form>
</template>

<script>
import { toHandlers } from 'vue'

export default {
    name: 'AddTask',
    data() {
        return {
            text: '',
            day: '',
            reminder: false,
        }
    },
    methods: {
        onSubmit(e) {
            e.preventDefault()

            if (!this.text) {
                alert('Please add a task')
                return
            }

            const newTask = {
                id: Math.floor(Math.random() * 100000),
                text: this.text,
                day: this.day,
                reminder: this.reminder
            }

            this.$emit('add-task', newTask)

            this.text = ''
            this.day = ''
            this.reminder = false
        }
    }
}
</script>

<style scoped>
.add-form {
    margin-bottom: 2rem;
}

.form-control {
    margin: 0.5rem 0;
}

.form-control label {
    display: block;
}

.form-control input {
    width: 100%;
    height: 2rem;
    padding: 0.5rem;
    font-size: 0.8rem;
}

.form-control-check {
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.form-control-check label {
    flex: 1;
}

.form-control-check input {
    flex: 2;
    height: 20px;
}
</style>
