// React_JS_crash_course/react-task-tracker/src/components/Footer.js
import { Link } from 'react-router-dom'


const Footer = () => {
  return (
    <footer className="px-4 text-center">
        <p>Copyright &copy; 2022</p>
        <Link to='/about' className=" text-blue-500 hover:underline">About</Link>
        {/* <a href="/about" className=" text-blue-500 hover:underline">About</a> */}
    </footer>
  )
}

export default Footer

// Vue_JS_crash_course/vue-crash-course/src/components/Footer.vue
<template>
    <footer>
        <p>
            Copyright &copy; {{ this.getYearFromDate(new Date()) }}
        </p>
        <a href="/about">About</a>
    </footer>
</template>

<script>
export default {
    name: 'Footer',
    methods: {
        getYearFromDate(date) {
            return new Date(date).getFullYear();
        },
    },
}
</script>

<style scoped>
footer {
    margin-top: 2rem;
    text-align: center;
}

a {
    color: #333;
}
</style>
