// React_JS_crash_course/react-task-tracker/src/components/Header.js
import PropTypes from 'prop-types'
import Button from './Button'

const Header = ({ title }) => {
    return (
        <header className="flex w-device justify-between items-center p-4">
            <h1 className="font-bold text-4xl text-center">Task Tracker</h1>
            <Button type="primary" text="Add" classes="text-white bg-green-600 hover:bg-green-700"/>
            {/* <Button text='Hello' />
            <Button text='World' /> */}
            {/* <p>{title}</p> */}
        </header>
    )
}

Header.defaultProps = {
    title: 'Default subtitle'
}

Header.propTypes = {
    title: PropTypes.string.isRequired,
}

// CSS in JS
// const headingStyle = {
//     color: 'red', 
//     backgroundColor: 'black'
// }

export default Header

// Vue_JS_crash_course/vue-crash-course/src/components/Header.vue
<template>
    <header>
        <h1>{{ title }}</h1>
        <Button text="Add task" color="green"/>
    </header>
</template>

<script>
import Button from './Button.vue'

export default {
    name: 'Header',
    props: {
        title: {
            type: String,
            default: 'Hello world',
        },
    },
    components: {
        Button,
    }
}
</script>

<style scoped>
header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1.5rem;
}
</style>
