// Vue_JS_crash_course/vue-crash-course/src/components/Task.vue
<template>
    <div class="task" :class="{ 'reminder' : task.reminder }">
        <h3>{{ task.text }} 
        <i class="fas fa-times"></i>
        </h3>
        <p>{{ task.day }}</p>
    </div>
</template>

<script>
export default {
    name: 'Task',
    props: {
        task: Object,
    }
}
</script>

<style scoped>
.fa-times {
    color: red;
}
.task {
    background: whitesmoke;
    margin: 0.5rem 0;
    padding: 0.5rem 1rem;
    cursor: pointer;
    border-radius: 0.2rem;
}

.task.reminder {
    border-left: 5px solid green;
}

.task h3 {
    display: flex;
    align-items: center;
    justify-content: space-between;
}
</style>

// React_JS_crash_course/react-task-tracker/src/components/Task.js
import { HiOutlineX } from "react-icons/hi";

const Task = ({ task, onDelete, onToggle }) => {
  return (
    <div onDoubleClick={ () => onToggle(task.id) } className={`px-4 py-2 bg-gray-200 rounded-sm ${task.reminder ? 'border-l-8 border-green-500' : ''}`}>
      <h3 className="text-lg font-bold flex justify-between items-center">{task.text}
        <HiOutlineX className="text-red-500 cursor-pointer w-6 h-6" onClick={ () => onDelete(task.id)} />
      </h3>
      <p>{task.day}</p>
    </div>
  )
}

export default Task
